name: i_quiz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  dio: ^5.2.1
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_database: ^10.0.16
  flutter_gen: ^5.3.1
  flutter_svg: ^1.1.5
  get: ^4.5.1
  google_sign_in: ^6.0.2
  intl: ^0.17.0 
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0  
  json_serializable: ^6.3.1  
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/jsons/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

  
  
